name: Functional Tests
description: Run Functional Tests
runs:
  using: 'composite'
  steps:
    - name: Run functional test
      shell: bash
      run: |
        npm ci
        npm run unit-testing
